/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facebook_presto_folly_FollyData */

#ifndef _Included_com_facebook_presto_folly_FollyData
#define _Included_com_facebook_presto_folly_FollyData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facebook_presto_folly_FollyData
 * Method:    getPage
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_facebook_presto_folly_FollyData_getPage
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
